import type { SinPathId, SinSkillId } from "../types";
import type { SinSkillDef, SinTransfig } from "./types";

function skill(def: SinSkillDef): SinSkillDef {
  return def;
}

export const SIN_SKILLS: SinSkillDef[] = [
  skill({
    id: "sin-flurry",
    name: "Шквал",
    description: "Серия уколов. Генератор комбо, основа любой ротации.",
    cooldown: 4.2,
    role: "generator",
    tags: ["attack", "melee", "combo"],
    kind: "agility",
    multiplier: 1.38,
    comboGain: 1,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 1,
    hitScale: 0.72,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-backstab",
    name: "Удар в спину",
    description: "Колющий удар с повышенным критом. Даёт 2 комбо.",
    cooldown: 6.2,
    role: "generator",
    tags: ["attack", "melee", "combo", "crit"],
    kind: "agility",
    multiplier: 1.95,
    comboGain: 2,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 16,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-venom",
    name: "Яд клинка",
    description: "Вгоняет токсин. Тикает, пока цель жива.",
    cooldown: 7,
    role: "apply",
    tags: ["attack", "poison", "duration"],
    kind: "agility",
    multiplier: 1.18,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 3,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-garrote",
    name: "Гаррота",
    description: "Перерезает горло: кровотечение и −скорость атаки цели.",
    cooldown: 9,
    role: "apply",
    tags: ["attack", "bleed", "duration"],
    kind: "agility",
    multiplier: 1.32,
    comboGain: 1,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 4,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 6,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-mark",
    name: "Метка убийцы",
    description: "Помечает добычу: навыки бьют сильнее, казнь мягче по порогу.",
    cooldown: 14,
    role: "maintain",
    tags: ["mark", "duration", "buff"],
    kind: "buff",
    multiplier: 0,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 10,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-vanish",
    name: "Исчезновение",
    description: "Роспуск в тень. Открывает засаду и копит заряд тени.",
    cooldown: 16,
    role: "setup",
    tags: ["stealth", "shade", "duration"],
    kind: "buff",
    multiplier: 0,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 1,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 3.4,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-ambush",
    name: "Засада",
    description: "Удар из скрытности. Нужна скрытность. Даёт сразу много комбо.",
    cooldown: 8,
    role: "opener",
    tags: ["attack", "stealth", "burst", "combo", "opener"],
    kind: "agility",
    multiplier: 2.45,
    comboGain: 3,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 10,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: true,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-eviscerate",
    name: "Потрошение",
    description: "Спендер: тратит всё комбо. Урон растёт с каждым очком.",
    cooldown: 7.2,
    role: "spender",
    tags: ["attack", "melee", "combo", "burst", "spender"],
    kind: "agility",
    multiplier: 0.78,
    comboGain: 0,
    comboCost: -1,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 6,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-fan",
    name: "Веер клинков",
    description: "Два клинка крест-накрест. Веерный удар, лёгкий генератор.",
    cooldown: 6.4,
    role: "generator",
    tags: ["attack", "aoe", "combo", "melee"],
    kind: "agility",
    multiplier: 1.22,
    comboGain: 1,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 1,
    hitScale: 0.8,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-shadowstep",
    name: "Теневой шаг",
    description: "Шаг сквозь цель. Заряд тени и короткий импульс урона.",
    cooldown: 10.5,
    role: "setup",
    tags: ["attack", "shade", "burst"],
    kind: "agility",
    multiplier: 1.48,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 1,
    shadeCost: 0,
    critBonus: 8,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-rupture",
    name: "Разрыв",
    description: "Детонирует яд. Чем больше стаков — тем больнее.",
    cooldown: 8.5,
    role: "spender",
    tags: ["attack", "poison", "burst", "spender"],
    kind: "agility",
    multiplier: 0.52,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: true,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-veil",
    name: "Завеса",
    description: "Следующие удары по вам ослаблены. Пассивно кормит тень.",
    cooldown: 15,
    role: "defensive",
    tags: ["defensive", "shade", "duration"],
    kind: "buff",
    multiplier: 0,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 3,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-clone",
    name: "Теневой двойник",
    description: "Эхо рядом с вами. Повторяет последний навык на 40%. Может перехватить удар.",
    cooldown: 18,
    role: "setup",
    tags: ["shade", "duration", "buff"],
    kind: "buff",
    multiplier: 0,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 1,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 8,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
  skill({
    id: "sin-execute",
    name: "Тихий приговор",
    description: "Финишер. Сильнее по раненой цели, ещё сильнее по меченой.",
    cooldown: 11,
    role: "finisher",
    tags: ["attack", "execute", "burst", "mark"],
    kind: "agility",
    multiplier: 2.15,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 8,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 0,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0.35,
  }),
  skill({
    id: "sin-nightblade",
    name: "Ночной клинок",
    description: "Боевой ритм: спешка навыков и проки ресурса с автоатак.",
    cooldown: 20,
    role: "maintain",
    tags: ["buff", "duration"],
    kind: "buff",
    multiplier: 0,
    comboGain: 0,
    comboCost: 0,
    poisonGain: 0,
    poisonConsume: false,
    shadeGain: 0,
    shadeCost: 0,
    critBonus: 0,
    extraHits: 0,
    hitScale: 1,
    stealthGrant: 0,
    markGrant: 0,
    nightbladeGrant: 12,
    veilHits: 0,
    cloneGrant: 0,
    bleedGrant: 0,
    requiresStealth: false,
    executeThreshold: 0,
  }),
];

export const SIN_SKILL_BY_ID: Record<SinSkillId, SinSkillDef> = Object.fromEntries(
  SIN_SKILLS.map((s) => [s.id, s]),
) as Record<SinSkillId, SinSkillDef>;

export const SIN_TRANSFIG: Record<SinPathId, Partial<Record<SinSkillId, SinTransfig>>> = {
  blade: {
    "sin-flurry": {
      name: "Танец клинков",
      description: "Три удара. +2 комбо. Крит танца выше.",
      tags: ["crit"],
      extraHits: 2,
      hitScale: 0.55,
      comboGain: 2,
      critBonus: 6,
      multiplier: 1.05,
    },
    "sin-backstab": {
      name: "Удар в сердце",
      description: "×2.2, огромный крит. По меченой цели ещё больнее.",
      multiplier: 2.2,
      critBonus: 24,
      comboGain: 2,
    },
    "sin-venom": {
      name: "Отравленный клинок",
      description: "Слабый яд, но следующие 2 генератора усилены.",
      poisonGain: 1,
      multiplier: 1.05,
    },
    "sin-garrote": {
      name: "Перерезание",
      description: "Кровотечение и +1 комбо. Цель бьёт медленнее.",
      comboGain: 1,
      bleedGrant: 7,
    },
    "sin-mark": {
      name: "Метка сердца",
      description: "Помеченная цель получает больше критов и казни.",
      markGrant: 12,
    },
    "sin-vanish": {
      name: "Короткий роспуск",
      description: "Короткая скрытность, но засада бьёт как приговор.",
      stealthGrant: 2.2,
      shadeGain: 1,
      cooldown: 14,
    },
    "sin-ambush": {
      name: "Удар из безмолвия",
      description: "Гарантированный крит из скрытности. +3 комбо.",
      multiplier: 2.7,
      critBonus: 100,
      comboGain: 3,
    },
    "sin-eviscerate": {
      name: "Потрошение безмолвия",
      description: "Тратит всё комбо. Крит-спендер ветки клинка.",
      multiplier: 0.86,
      critBonus: 14,
    },
    "sin-fan": {
      name: "Стальной веер",
      description: "Два удара, +1 комбо. После шквала — ещё крит.",
      extraHits: 1,
      comboGain: 1,
      critBonus: 6,
      multiplier: 1.28,
    },
    "sin-shadowstep": {
      name: "Шаг к сердцу",
      description: "Следующий удар в спину усилен. +1 тень.",
      multiplier: 1.6,
      shadeGain: 1,
    },
    "sin-rupture": {
      name: "Вскрытие",
      description: "Тратит яд и часть комбо. Гибридный спендер.",
      poisonConsume: true,
      comboCost: 2,
      multiplier: 0.62,
    },
    "sin-veil": {
      name: "Завеса клинка",
      description: "3 удара −40%. После блока генератор критует.",
      veilHits: 3,
    },
    "sin-clone": {
      name: "Клинок-эхо",
      description: "Короткий двойник, бьёт слабее, но даёт комбо-прок.",
      cloneGrant: 6,
      shadeGain: 0,
    },
    "sin-execute": {
      name: "Приговор",
      description: "×2.4 ниже 40% HP. На 3+ комбо порог 55%.",
      multiplier: 2.4,
      executeThreshold: 0.4,
      critBonus: 10,
    },
    "sin-nightblade": {
      name: "Ритм убийцы",
      description: "Спешка и шанс +1 комбо с автоатаки.",
      nightbladeGrant: 14,
      tags: ["combo", "buff"],
    },
  },
  venom: {
    "sin-flurry": {
      name: "Ядовитые иглы",
      description: "Каждый удар капает яд. +2 яда, +1 комбо.",
      tags: ["poison"],
      extraHits: 1,
      poisonGain: 2,
      comboGain: 1,
      multiplier: 1.2,
    },
    "sin-backstab": {
      name: "Укол железы",
      description: "Впрыскивает +3 яда. Если комбо ≥2 — ещё +2.",
      poisonGain: 3,
      comboGain: 1,
      multiplier: 1.7,
      tags: ["poison"],
    },
    "sin-venom": {
      name: "Концентрированный токсин",
      description: "+5 стаков. Тики этой ветки жирнее.",
      poisonGain: 5,
      multiplier: 1.1,
      cooldown: 6.4,
    },
    "sin-garrote": {
      name: "Некротический зажим",
      description: "Кровотечение + яд. Цель гниёт с двух сторон.",
      poisonGain: 2,
      bleedGrant: 7,
      tags: ["poison", "bleed"],
    },
    "sin-mark": {
      name: "Метка чумы",
      description: "Меченая цель получает +25% урона ядом.",
      markGrant: 12,
      tags: ["poison", "mark"],
    },
    "sin-vanish": {
      name: "Ядовитый туман",
      description: "Скрытность накладывает +2 яда сразу.",
      stealthGrant: 3,
      poisonGain: 2,
      shadeGain: 1,
    },
    "sin-ambush": {
      name: "Укус из травы",
      description: "Засада впрыскивает +6 яда.",
      poisonGain: 6,
      multiplier: 2.1,
      comboGain: 2,
      tags: ["poison", "opener"],
    },
    "sin-eviscerate": {
      name: "Вскрытие железы",
      description: "Тратит комбо, чтобы усилить следующий Разрыв.",
      multiplier: 0.55,
      comboCost: -1,
    },
    "sin-fan": {
      name: "Чумной веер",
      description: "Разносит яд. +3 стака за применение.",
      poisonGain: 3,
      extraHits: 1,
      tags: ["poison", "aoe"],
      multiplier: 1.15,
    },
    "sin-shadowstep": {
      name: "Шаг через чашу",
      description: "Оставляет облако: мгновенный тик яда.",
      poisonGain: 2,
      shadeGain: 1,
      multiplier: 1.3,
    },
    "sin-rupture": {
      name: "Детонация яда",
      description: "Главный спендер чаши. Сжигает все стаки в взрыв.",
      poisonConsume: true,
      multiplier: 0.72,
      cooldown: 7.6,
    },
    "sin-veil": {
      name: "Токсичная дымка",
      description: "Защита. Атакующий получает +1 яд за удар.",
      veilHits: 3,
      tags: ["poison", "defensive"],
    },
    "sin-clone": {
      name: "Чумное эхо",
      description: "Двойник тикает ядом вместе с вами.",
      cloneGrant: 9,
      shadeGain: 1,
      tags: ["poison", "shade"],
    },
    "sin-execute": {
      name: "Последняя капля",
      description: "Казнь дополнительно детонирует 40% оставшегося яда.",
      executeThreshold: 0.38,
      multiplier: 2.0,
    },
    "sin-nightblade": {
      name: "Аура тлена",
      description: "Автоатаки накладывают +1 яд.",
      nightbladeGrant: 14,
      tags: ["poison", "buff"],
    },
  },
  phantom: {
    "sin-flurry": {
      name: "Удары тени",
      description: "Шквал из эха. +1 тень, +1 комбо.",
      tags: ["shade"],
      shadeGain: 1,
      comboGain: 1,
      extraHits: 1,
      multiplier: 1.25,
    },
    "sin-backstab": {
      name: "Удар из ниоткуда",
      description: "Если есть скрытность или тень — ×1.35.",
      tags: ["shade", "stealth"],
      multiplier: 1.9,
      comboGain: 2,
      critBonus: 12,
    },
    "sin-venom": {
      name: "Яд пустоты",
      description: "Редкий яд, дающий заряд тени.",
      poisonGain: 2,
      shadeGain: 1,
      multiplier: 1.1,
    },
    "sin-garrote": {
      name: "Удавка призрака",
      description: "Из скрытности длится дольше. +1 тень.",
      bleedGrant: 7,
      shadeGain: 1,
      tags: ["stealth", "bleed"],
    },
    "sin-mark": {
      name: "Метка добычи",
      description: "Клон бьёт меченую цель. Навыки из тени жирнее.",
      markGrant: 11,
      tags: ["mark", "shade"],
    },
    "sin-vanish": {
      name: "Роспуск",
      description: "Длинная скрытность и +2 тени. Корень ветки.",
      stealthGrant: 4.2,
      shadeGain: 2,
      cooldown: 15,
    },
    "sin-ambush": {
      name: "Из ниоткуда",
      description: "Тратит 1 тень сверх скрытности. Огромный opener.",
      shadeCost: 1,
      multiplier: 2.85,
      comboGain: 3,
      critBonus: 18,
    },
    "sin-eviscerate": {
      name: "Разорвать эхо",
      description: "Тратит комбо и 1 тень. Эхо бьёт следом.",
      comboCost: -1,
      shadeCost: 1,
      multiplier: 0.8,
    },
    "sin-fan": {
      name: "Призрачные клинки",
      description: "Клон повторяет веер, если активен.",
      extraHits: 1,
      tags: ["shade", "aoe"],
      multiplier: 1.2,
    },
    "sin-shadowstep": {
      name: "Сквозь завесу",
      description: "Даёт 1.2с скрытности и +1 тень.",
      stealthGrant: 1.2,
      shadeGain: 1,
      multiplier: 1.55,
    },
    "sin-rupture": {
      name: "Разрыв эха",
      description: "Если яда < 4 — детонирует текущую тень (минимум 1). Иначе сжигает яд.",
      poisonConsume: true,
      multiplier: 0.58,
    },
    "sin-veil": {
      name: "Призрачная плоть",
      description: "3 удара −50% и +1 тень.",
      veilHits: 3,
      shadeGain: 1,
    },
    "sin-clone": {
      name: "Эхо",
      description: "Долгий двойник. Повторяет последний навык на 40%.",
      cloneGrant: 11,
      shadeGain: 1,
      cooldown: 16,
    },
    "sin-execute": {
      name: "Стирание",
      description: "В окне HP — полная казнь. Вне окна при 2+ тени: ×1.15 и тратит 2 тени.",
      executeThreshold: 0.35,
      shadeCost: 0,
      multiplier: 2.2,
    },
    "sin-nightblade": {
      name: "Танец призрака",
      description: "Крит навыка даёт заряд тени. Спешка.",
      nightbladeGrant: 13,
      tags: ["shade", "buff"],
    },
  },
};

export function isSinSkillId(id: string | null | undefined): id is SinSkillId {
  return !!id && id in SIN_SKILL_BY_ID;
}
